<?php


namespace MisterIcy\ExcelWriter\Handlers;


use MisterIcy\ExcelWriter\Generator\BasicGenerator;
use MisterIcy\ExcelWriter\Generator\GeneratorInterface;

final class MetadataHandler extends AbstractHandler
{
    /**
     * @param BasicGenerator $generator
     * @return HandlerInterface
     */
    public function handle(GeneratorInterface $generator): HandlerInterface
    {
        $spreadsheet = $generator->getSpreadsheet();

        $spreadsheet->getProperties()
            ->setCreator('mistericy/excel-writer')
            ->setTitle('Test Excel File');

        return parent::handle($generator); // TODO: Change the autogenerated stub
    }

}